---
- hosts: nginx
  tasks:
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true
    - name: Enable Nginx
      ansible.builtin.systemd:
        state: started
        name: nginx
        enabled: true