---
- name: Install epel-release
  yum:
    name: epel-release
    state: present

- name: Install Nginx Web Server on RedHat Family
  yum:
    name: nginx
    state: present
  notify:
    - nginx systemd
